"""Validate the easy same-episode pair catalog.

The catalog is generated by build_easy_pair_catalog.py. These tests check the
persisted artifacts without regenerating them.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest
import torch

from env.pusht_wm_env import PushTWMEnv

REPO_ROOT = Path(__file__).resolve().parents[2]
CATALOG_PATH = REPO_ROOT / "tests" / "goal_selection" / "easy_pair_catalog.json"
REQUIRED_IDS = tuple(f"easy_pair_{i}" for i in range(1, 6))


def _load_catalog() -> dict:
    if not CATALOG_PATH.exists():
        pytest.skip(f"easy-pair catalog not built yet: {CATALOG_PATH}")
    return json.loads(CATALOG_PATH.read_text())


def _pairs(catalog: dict) -> dict:
    return {k: v for k, v in catalog.items() if k.startswith("easy_pair_")}


def test_catalog_has_exactly_five_pairs():
    catalog = _load_catalog()
    pairs = _pairs(catalog)
    assert set(pairs) == set(REQUIRED_IDS)
    assert len(pairs) == 5


def test_each_pair_matches_easy_constraints():
    catalog = _load_catalog()
    for pair_id, pair in _pairs(catalog).items():
        start = pair["start"]
        goal = pair["goal"]
        assert start["hdf5_path"] == goal["hdf5_path"], pair_id
        assert goal["frame_idx"] - start["frame_idx"] == 5, pair_id
        assert 4.0 <= float(pair["distance_px"]) <= 18.0, pair_id
        assert float(pair["abs_delta_theta_deg"]) <= 30.0, pair_id
        assert float(start["icp_residual"]) < 0.5, pair_id
        assert float(goal["icp_residual"]) < 0.5, pair_id


def test_goal_pt_files_load_via_env_load_goal():
    catalog = _load_catalog()
    for pair_id, pair in _pairs(catalog).items():
        path = REPO_ROOT / pair["goal"]["state_pt_path"]
        assert path.exists(), f"{pair_id} goal .pt missing at {path}"
        goal = PushTWMEnv.load_goal(None, path)
        assert goal["state"].shape == (4,)
        for key in ("cx", "cy", "sin_theta", "cos_theta", "theta_deg"):
            assert key in goal


def test_episode_variety_or_documented_fallback():
    catalog = _load_catalog()
    pairs = _pairs(catalog)
    episodes = [Path(p["start"]["hdf5_path"]).stem for p in pairs.values()]
    unique_episodes = set(episodes)
    metadata = catalog["_metadata"]

    # The requested ideal is 5 different episodes. The current mini split has
    # no qualifying episode_0 gap-5 pair (max movement is documented as ~1 px),
    # so require max feasible coverage plus an explicit fallback note.
    assert len(unique_episodes) == 4
    assert metadata["qualifying_pairs_per_episode"]["0"] == 0
    assert any(
        note.get("episode") == 0 and "zero qualifying" in note.get("reason", "")
        for note in metadata["fallback_notes"]
    )


def test_round_trip_goal_payload_matches_catalog():
    catalog = _load_catalog()
    for pair_id, pair in _pairs(catalog).items():
        goal = pair["goal"]
        path = REPO_ROOT / goal["state_pt_path"]
        payload = torch.load(str(path), map_location="cpu", weights_only=False)
        assert payload["meta"]["round_tripped"] is True
        assert payload["meta"]["source_frame"] == goal["frame_idx"]
        assert payload["cx"] == pytest.approx(goal["round_tripped_cx"])
        assert payload["cy"] == pytest.approx(goal["round_tripped_cy"])
        assert payload["theta_deg"] == pytest.approx(goal["round_tripped_theta_deg"])
        assert "raw_cx" in goal and "raw_cy" in goal and "raw_theta_deg" in goal
        assert 0.0 < float(pair["round_tripped_distance_px"]) <= 18.0
        assert abs(float(pair["round_tripped_delta_theta_deg"])) <= 30.0
